# Generated by Django 4.0.2 on 2023-10-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('ability', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='pokemon_images/')),
                ('evolution', models.CharField(max_length=100)),
            ],
        ),
    ]
